package tests

import (
	"context"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"regexp"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/stretchr/testify/require"
)

// The hosted MCP service under test, as published by tests/docker-compose.yml.
// mcpBaseURL is simultaneously the OAuth issuer, the base of every discovery
// document, and the prefix of the RFC 8707 resource identifier, so it must be
// byte-for-byte the URL the MCP container is configured with (MCP_BASE_URL).
const (
	mcpBaseURL     = "http://localhost:8082"
	mcpEndpointURL = mcpBaseURL + "/mcp"
	mcpResource    = mcpEndpointURL
)

// Identity of the dedicated MCP integration-test user. Every MCP OAuth flow
// authenticates as this Firebase UID, so MCP API-key rotation can never
// invalidate the shared user the other integration tests authenticate with.
const (
	mcpTestUserID     = "mcp-test-user-id"
	mcpTestUserEmail  = "mcp-test@httpsms.com"
	mcpTestUserAPIKey = "mcp-test-user-api-key"
)

// Identity of the dedicated rate-limit user. Rate-limit budgets are per user
// and per tool, so exhausting a bucket as this user never affects the tools
// the functional tests call as mcpTestUserID.
const (
	mcpRateLimitUserID    = "mcp-rate-limit-user-id"
	mcpRateLimitUserEmail = "mcp-rate-limit@httpsms.com"
)

// Test-only key material and Firebase configuration, generated by
// generate-firebase-credentials.sh and mounted into the MCP container.
const (
	mcpSigningKeyPath   = "mcp-test-signing-key.pem"
	mcpSigningKeyID     = "mcp-test-key"
	firebaseProjectID   = "httpsms-test"
	firebaseIssuer      = "https://securetoken.google.com/" + firebaseProjectID
	mcpAPIAudience      = "http://api:8000"
	mcpProtocolLatest   = "2026-07-28"
	mcpProtocolPrevious = "2025-11-25"
)

// mcpToolNames is the exact, approved MCP tool catalog. The integration suite
// asserts the served catalog matches it exactly, so adding or renaming a tool
// without updating the design is caught here.
var mcpToolNames = []string{
	"list_phones",
	"send_sms",
	"list_message_threads",
	"list_thread_messages",
	"list_incoming_messages",
	"create_phone_api_key",
	"rotate_user_api_key",
}

// mcpAllScopes is every scope the MCP service issues, in published order.
var mcpAllScopes = []string{
	"phones:read",
	"messages:read",
	"messages:send",
	"phone-api-keys:write",
	"user-api-key:rotate",
}

// transactionIDPattern extracts the authorization transaction ID from the
// rendered consent page. The tests drive the consent form exactly as the
// browser would: they never reach into the MCP service's Redis state.
var transactionIDPattern = regexp.MustCompile(`name="transaction_id" value="([^"]+)"`)

// signingKeyOnce loads the generated RSA signing key at most once per test
// binary: every test that mints a Firebase ID token or an API delegation
// token shares it.
var (
	signingKeyOnce sync.Once
	signingKey     *rsa.PrivateKey
	signingKeyErr  error
)

// tokenResponse is the RFC 6749 token endpoint success body.
type tokenResponse struct {
	AccessToken  string `json:"access_token"`
	TokenType    string `json:"token_type"`
	ExpiresIn    int64  `json:"expires_in"`
	RefreshToken string `json:"refresh_token"`
	Scope        string `json:"scope"`
}

// oauthErrorResponse is the RFC 6749 Section 5.2 error body every direct
// (non-redirect) OAuth error carries.
type oauthErrorResponse struct {
	Error            string `json:"error"`
	ErrorDescription string `json:"error_description"`
}

// mcpSigningKey returns the RSA private key the MCP container signs with and
// the tests sign test Firebase ID tokens and API delegation tokens with.
func mcpSigningKey(t *testing.T) *rsa.PrivateKey {
	t.Helper()

	signingKeyOnce.Do(func() {
		contents, err := os.ReadFile(mcpSigningKeyPath)
		if err != nil {
			signingKeyErr = fmt.Errorf("read %s: %w", mcpSigningKeyPath, err)
			return
		}

		block, _ := pem.Decode(contents)
		if block == nil {
			signingKeyErr = fmt.Errorf("%s does not contain a PEM block", mcpSigningKeyPath)
			return
		}

		if key, err := x509.ParsePKCS1PrivateKey(block.Bytes); err == nil {
			signingKey = key
			return
		}

		parsed, err := x509.ParsePKCS8PrivateKey(block.Bytes)
		if err != nil {
			signingKeyErr = fmt.Errorf("parse %s: %w", mcpSigningKeyPath, err)
			return
		}

		key, ok := parsed.(*rsa.PrivateKey)
		if !ok {
			signingKeyErr = fmt.Errorf("%s is a %T, not an RSA private key", mcpSigningKeyPath, parsed)
			return
		}
		signingKey = key
	})

	require.NoError(t, signingKeyErr, "run `bash generate-firebase-credentials.sh` before the MCP integration tests")
	require.NotNil(t, signingKey)

	return signingKey
}

// signFirebaseTestToken mints a Firebase-style ID token for userID that the
// MCP service verifies against the WireMock-served certificate for
// mcpSigningKeyID. It is the deterministic, offline stand-in for a real
// browser Firebase sign-in.
func signFirebaseTestToken(t *testing.T, userID, email string) string {
	t.Helper()

	now := time.Now().UTC()
	claims := jwt.MapClaims{
		"iss":       firebaseIssuer,
		"aud":       firebaseProjectID,
		"sub":       userID,
		"user_id":   userID,
		"email":     email,
		"auth_time": now.Add(-time.Minute).Unix(),
		"iat":       now.Add(-time.Minute).Unix(),
		"exp":       now.Add(time.Hour).Unix(),
	}

	token := jwt.NewWithClaims(jwt.SigningMethodRS256, claims)
	token.Header["kid"] = mcpSigningKeyID

	signed, err := token.SignedString(mcpSigningKey(t))
	require.NoError(t, err)

	return signed
}

// signAPIDelegationToken mints a downstream API delegation token exactly as
// the MCP service's tool handlers do: issued by the MCP service, audienced to
// the httpSMS API, and bound to one HTTP method and path.
//
// It exists so the tests can prove the API's own delegated-token verifier
// enforces that binding, without going through a tool that can only ever mint
// a correctly bound token.
func signAPIDelegationToken(t *testing.T, userID string, scopes []string, method, path string, options ...func(jwt.MapClaims)) string {
	t.Helper()

	now := time.Now().UTC()
	claims := jwt.MapClaims{
		"iss":         mcpBaseURL,
		"aud":         mcpAPIAudience,
		"sub":         userID,
		"scopes":      scopes,
		"http_method": method,
		"http_path":   path,
		"iat":         now.Unix(),
		"nbf":         now.Unix(),
		"exp":         now.Add(2 * time.Minute).Unix(),
		"jti":         uuid.NewString(),
	}
	for _, option := range options {
		option(claims)
	}

	token := jwt.NewWithClaims(jwt.SigningMethodRS256, claims)
	token.Header["kid"] = mcpSigningKeyID

	signed, err := token.SignedString(mcpSigningKey(t))
	require.NoError(t, err)

	return signed
}

// signFirebaseTokenWithClaims mints a Firebase-style ID token for the MCP test
// user with mutate applied to its claims, for asserting that a token the MCP
// service must reject really is rejected.
func signFirebaseTokenWithClaims(t *testing.T, mutate func(claims jwt.MapClaims)) string {
	t.Helper()

	now := time.Now().UTC()
	claims := jwt.MapClaims{
		"iss":       firebaseIssuer,
		"aud":       firebaseProjectID,
		"sub":       mcpTestUserID,
		"user_id":   mcpTestUserID,
		"email":     mcpTestUserEmail,
		"auth_time": now.Add(-time.Minute).Unix(),
		"iat":       now.Add(-time.Minute).Unix(),
		"exp":       now.Add(time.Hour).Unix(),
	}
	mutate(claims)

	token := jwt.NewWithClaims(jwt.SigningMethodRS256, claims)
	token.Header["kid"] = mcpSigningKeyID

	signed, err := token.SignedString(mcpSigningKey(t))
	require.NoError(t, err)

	return signed
}

// signFirebaseTokenWithKeyID mints an otherwise valid Firebase-style ID token
// under a key ID the Firebase certificate endpoint does not publish.
func signFirebaseTokenWithKeyID(t *testing.T, keyID string) string {
	t.Helper()

	now := time.Now().UTC()
	token := jwt.NewWithClaims(jwt.SigningMethodRS256, jwt.MapClaims{
		"iss":       firebaseIssuer,
		"aud":       firebaseProjectID,
		"sub":       mcpTestUserID,
		"user_id":   mcpTestUserID,
		"email":     mcpTestUserEmail,
		"auth_time": now.Add(-time.Minute).Unix(),
		"iat":       now.Add(-time.Minute).Unix(),
		"exp":       now.Add(time.Hour).Unix(),
	})
	token.Header["kid"] = keyID

	signed, err := token.SignedString(mcpSigningKey(t))
	require.NoError(t, err)

	return signed
}

// pkcePair returns a fresh RFC 7636 code verifier and its S256 challenge.
func pkcePair(t *testing.T) (verifier string, challenge string) {
	t.Helper()

	raw := make([]byte, 32)
	_, err := rand.Read(raw)
	require.NoError(t, err)

	verifier = base64.RawURLEncoding.EncodeToString(raw)
	sum := sha256.Sum256([]byte(verifier))

	return verifier, base64.RawURLEncoding.EncodeToString(sum[:])
}

// noRedirectClient returns an HTTP client that surfaces redirects instead of
// following them: an authorization response redirects to a loopback client
// URL nothing is listening on, and the test needs to read the Location header.
func noRedirectClient() *http.Client {
	return &http.Client{
		Timeout: 30 * time.Second,
		CheckRedirect: func(*http.Request, []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}
}

// registerMCPOAuthClient performs RFC 7591 Dynamic Client Registration
// against the MCP service and returns the assigned client ID and the
// redirect URI it was registered with.
func registerMCPOAuthClient(t *testing.T) (clientID string, redirectURI string) {
	t.Helper()

	redirectURI = "http://localhost:53682/callback/" + uuid.NewString()

	body, err := json.Marshal(map[string]any{
		"client_name":                "httpSMS MCP integration tests",
		"redirect_uris":              []string{redirectURI},
		"grant_types":                []string{"authorization_code", "refresh_token"},
		"response_types":             []string{"code"},
		"token_endpoint_auth_method": "none",
	})
	require.NoError(t, err)

	response, responseBody := doMCPRequest(t, http.MethodPost, mcpBaseURL+"/oauth/register", "application/json", strings.NewReader(string(body)))
	require.Equal(t, http.StatusCreated, response.StatusCode, "register: %s", responseBody)

	var registered struct {
		ClientID     string   `json:"client_id"`
		RedirectURIs []string `json:"redirect_uris"`
	}
	require.NoError(t, json.Unmarshal([]byte(responseBody), &registered))
	require.NotEmpty(t, registered.ClientID)
	require.Equal(t, []string{redirectURI}, registered.RedirectURIs)

	return registered.ClientID, redirectURI
}

// authorizationCodeParams is one complete, already-approved authorization: the
// code the token endpoint will redeem plus every value the token request must
// echo back.
type authorizationCodeParams struct {
	Code        string
	ClientID    string
	RedirectURI string
	Verifier    string
	State       string
	Issuer      string
	Scopes      []string
}

// requestAuthorizationCode drives a complete browser authorization for userID:
// dynamic client registration, GET /oauth/authorize, and the consent POST that
// carries a signed Firebase ID token. It returns everything needed to redeem
// the resulting code.
func requestAuthorizationCode(t *testing.T, userID, email string, scopes []string) authorizationCodeParams {
	t.Helper()

	clientID, redirectURI := registerMCPOAuthClient(t)
	verifier, challenge := pkcePair(t)
	state := uuid.NewString()

	transactionID := startAuthorization(t, clientID, redirectURI, state, challenge, scopes)
	location := completeFirebaseConsent(t, transactionID, signFirebaseTestToken(t, userID, email), scopes, http.StatusFound)

	redirected, err := url.Parse(location)
	require.NoError(t, err)
	require.Empty(t, redirected.Query().Get("error"), "authorization failed: %s", location)

	code := redirected.Query().Get("code")
	require.NotEmpty(t, code, "no authorization code in %s", location)
	require.Equal(t, state, redirected.Query().Get("state"))

	return authorizationCodeParams{
		Code:        code,
		ClientID:    clientID,
		RedirectURI: redirectURI,
		Verifier:    verifier,
		State:       state,
		Issuer:      redirected.Query().Get("iss"),
		Scopes:      scopes,
	}
}

// startAuthorization performs GET /oauth/authorize and returns the
// authorization transaction ID embedded in the rendered consent page.
func startAuthorization(t *testing.T, clientID, redirectURI, state, challenge string, scopes []string) string {
	t.Helper()

	response, body := getAuthorizePage(t, url.Values{
		"client_id":             {clientID},
		"redirect_uri":          {redirectURI},
		"response_type":         {"code"},
		"state":                 {state},
		"code_challenge":        {challenge},
		"code_challenge_method": {"S256"},
		"resource":              {mcpResource},
		"scope":                 {strings.Join(scopes, " ")},
	})
	require.Equal(t, http.StatusOK, response.StatusCode, "authorize: %s", body)

	match := transactionIDPattern.FindStringSubmatch(body)
	require.Len(t, match, 2, "no transaction_id in the consent page")

	return match[1]
}

// getAuthorizePage performs GET /oauth/authorize with query and returns the
// raw response and body, without following any redirect.
func getAuthorizePage(t *testing.T, query url.Values) (*http.Response, string) {
	t.Helper()

	return doMCPRequest(t, http.MethodGet, mcpBaseURL+"/oauth/authorize?"+query.Encode(), "", nil)
}

// completeFirebaseConsent posts the consent form (transaction, Firebase ID
// token, approved scopes) and returns the Location header of the resulting
// redirect. expectedStatus lets a caller assert a rejected consent instead.
func completeFirebaseConsent(t *testing.T, transactionID, idToken string, approvedScopes []string, expectedStatus int) string {
	t.Helper()

	form := url.Values{
		"transaction_id": {transactionID},
		"id_token":       {idToken},
	}
	form["approved_scopes"] = approvedScopes

	response, body := doMCPRequest(
		t,
		http.MethodPost,
		mcpBaseURL+"/oauth/firebase/complete",
		"application/x-www-form-urlencoded",
		strings.NewReader(form.Encode()),
	)
	require.Equal(
		t,
		expectedStatus,
		response.StatusCode,
		"firebase complete: %s\n(an unexpected 401 usually means WireMock is serving a certificate that no longer matches "+
			"%s: re-run `bash generate-firebase-credentials.sh` and `docker compose up -d --force-recreate wiremock mcp`)",
		body,
		mcpSigningKeyPath,
	)

	return response.Header.Get("Location")
}

// redeemAuthorizationCode posts the authorization_code grant built from params
// (after applying any overrides) and returns the raw response and body.
func redeemAuthorizationCode(t *testing.T, params authorizationCodeParams, overrides ...func(url.Values)) (*http.Response, string) {
	t.Helper()

	form := url.Values{
		"grant_type":    {"authorization_code"},
		"code":          {params.Code},
		"code_verifier": {params.Verifier},
		"client_id":     {params.ClientID},
		"redirect_uri":  {params.RedirectURI},
		"resource":      {mcpResource},
	}
	for _, override := range overrides {
		override(form)
	}

	return doMCPRequest(t, http.MethodPost, mcpBaseURL+"/oauth/token", "application/x-www-form-urlencoded", strings.NewReader(form.Encode()))
}

// refreshTokens posts the refresh_token grant and returns the raw response and
// body.
func refreshTokens(t *testing.T, refreshToken, clientID string, overrides ...func(url.Values)) (*http.Response, string) {
	t.Helper()

	form := url.Values{
		"grant_type":    {"refresh_token"},
		"refresh_token": {refreshToken},
		"client_id":     {clientID},
	}
	for _, override := range overrides {
		override(form)
	}

	return doMCPRequest(t, http.MethodPost, mcpBaseURL+"/oauth/token", "application/x-www-form-urlencoded", strings.NewReader(form.Encode()))
}

// completeOAuthCodeFlow runs the complete PKCE authorization-code flow for the
// MCP test user and returns the issued tokens.
func completeOAuthCodeFlow(t *testing.T, scopes []string) tokenResponse {
	t.Helper()
	return completeOAuthCodeFlowAs(t, mcpTestUserID, mcpTestUserEmail, scopes)
}

// completeOAuthCodeFlowAs runs the complete PKCE authorization-code flow for
// an arbitrary Firebase UID and returns the issued tokens.
func completeOAuthCodeFlowAs(t *testing.T, userID, email string, scopes []string) tokenResponse {
	t.Helper()

	params := requestAuthorizationCode(t, userID, email, scopes)

	response, body := redeemAuthorizationCode(t, params)
	require.Equal(t, http.StatusOK, response.StatusCode, "token: %s", body)

	var tokens tokenResponse
	require.NoError(t, json.Unmarshal([]byte(body), &tokens))
	require.NotEmpty(t, tokens.AccessToken)
	require.NotEmpty(t, tokens.RefreshToken)
	require.Equal(t, "Bearer", tokens.TokenType)

	return tokens
}

// bearerTransport attaches a fixed bearer token to every request.
type bearerTransport struct {
	token string
	next  http.RoundTripper
}

func (t *bearerTransport) RoundTrip(request *http.Request) (*http.Response, error) {
	cloned := request.Clone(request.Context())
	cloned.Header.Set("Authorization", "Bearer "+t.token)

	next := t.next
	if next == nil {
		next = http.DefaultTransport
	}
	return next.RoundTrip(cloned)
}

// newMCPClient connects the official MCP Go SDK client to the running MCP
// service over authenticated Streamable HTTP and returns the live session.
//
// protocolVersion must be mcpProtocolLatest: the SDK client always negotiates
// the newest protocol version it supports and offers no exported knob to
// downgrade it. Compatibility with mcpProtocolPrevious is covered by
// callLegacyMCP, which speaks the wire protocol directly and is therefore the
// only way to assert a legacy initialize handshake at all.
func newMCPClient(t *testing.T, accessToken, protocolVersion string, options ...func(*mcp.ClientOptions)) *mcp.ClientSession {
	t.Helper()
	require.Equal(t, mcpProtocolLatest, protocolVersion, "the SDK client only negotiates %s; use callLegacyMCP for %s", mcpProtocolLatest, mcpProtocolPrevious)

	clientOptions := &mcp.ClientOptions{}
	for _, option := range options {
		option(clientOptions)
	}

	client := mcp.NewClient(&mcp.Implementation{Name: "httpsms-integration-tests", Version: "test"}, clientOptions)

	transport := &mcp.StreamableClientTransport{
		Endpoint: mcpEndpointURL,
		HTTPClient: &http.Client{
			Timeout:   60 * time.Second,
			Transport: &bearerTransport{token: accessToken},
		},
		// The MCP service is stateless and never initiates a request of its
		// own, so a standalone SSE stream would only add a connection to
		// tear down.
		DisableStandaloneSSE: true,
	}

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	session, err := client.Connect(ctx, transport, nil)
	require.NoError(t, err)
	t.Cleanup(func() { _ = session.Close() })

	return session
}

// callMCPTool calls name with arguments and fails the test on a protocol-level
// error. A tool-level error (CallToolResult.IsError) is returned to the
// caller, which is what every "this call must be refused" assertion inspects.
func callMCPTool(t *testing.T, session *mcp.ClientSession, name string, arguments any) *mcp.CallToolResult {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	result, err := session.CallTool(ctx, &mcp.CallToolParams{Name: name, Arguments: arguments})
	require.NoError(t, err, "tool %s", name)
	require.NotNil(t, result)

	return result
}

// toolResultText concatenates every text content block of result, which is
// where a tool-level error message is carried.
func toolResultText(result *mcp.CallToolResult) string {
	var builder strings.Builder
	for _, content := range result.Content {
		if text, ok := content.(*mcp.TextContent); ok {
			builder.WriteString(text.Text)
		}
	}
	return builder.String()
}

// decodeToolOutput decodes a successful tool call's structured output into out.
func decodeToolOutput(t *testing.T, result *mcp.CallToolResult, out any) {
	t.Helper()
	require.False(t, result.IsError, "tool call failed: %s", toolResultText(result))
	require.NotNil(t, result.StructuredContent, "tool call returned no structured content")

	encoded, err := json.Marshal(result.StructuredContent)
	require.NoError(t, err)
	require.NoError(t, json.Unmarshal(encoded, out))
}

// jsonRPCResponse is a decoded JSON-RPC response from the MCP endpoint, used
// by the raw-protocol helpers below.
type jsonRPCResponse struct {
	JSONRPC string          `json:"jsonrpc"`
	ID      any             `json:"id"`
	Result  json.RawMessage `json:"result"`
	Error   *struct {
		Code    int             `json:"code"`
		Message string          `json:"message"`
		Data    json.RawMessage `json:"data"`
	} `json:"error"`
}

// callLegacyMCP sends a single JSON-RPC request to the MCP endpoint over raw
// Streamable HTTP, announcing protocolVersion. It is how the suite exercises
// the 2025-11-25 protocol, which the SDK client cannot be asked to negotiate.
func callLegacyMCP(t *testing.T, accessToken, protocolVersion, method string, params any) (*http.Response, jsonRPCResponse) {
	t.Helper()

	payload := map[string]any{
		"jsonrpc": "2.0",
		"id":      uuid.NewString(),
		"method":  method,
	}
	if params != nil {
		payload["params"] = params
	}

	body, err := json.Marshal(payload)
	require.NoError(t, err)

	request, err := http.NewRequest(http.MethodPost, mcpEndpointURL, strings.NewReader(string(body)))
	require.NoError(t, err)
	request.Header.Set("Content-Type", "application/json")
	request.Header.Set("Accept", "application/json, text/event-stream")
	if accessToken != "" {
		request.Header.Set("Authorization", "Bearer "+accessToken)
	}
	if protocolVersion != "" && method != "initialize" {
		request.Header.Set("Mcp-Protocol-Version", protocolVersion)
	}

	response, err := noRedirectClient().Do(request)
	require.NoError(t, err)
	defer func() { _ = response.Body.Close() }()

	raw, err := io.ReadAll(response.Body)
	require.NoError(t, err)

	var decoded jsonRPCResponse
	if len(raw) > 0 && response.StatusCode < http.StatusBadRequest {
		require.NoError(t, json.Unmarshal(raw, &decoded), "response body: %s", string(raw))
	}

	return response, decoded
}

// doMCPRequest performs a single HTTP request against the MCP service and
// returns the response (with its body already drained and closed) and the body.
func doMCPRequest(t *testing.T, method, requestURL, contentType string, body io.Reader) (*http.Response, string) {
	t.Helper()

	request, err := http.NewRequest(method, requestURL, body)
	require.NoError(t, err)
	if contentType != "" {
		request.Header.Set("Content-Type", contentType)
	}

	response, err := noRedirectClient().Do(request)
	require.NoError(t, err)
	defer func() { _ = response.Body.Close() }()

	raw, err := io.ReadAll(response.Body)
	require.NoError(t, err)

	return response, string(raw)
}

// getJSON fetches requestURL and decodes the JSON body into out, returning the
// response for status/header assertions.
func getJSON(t *testing.T, requestURL string, out any) *http.Response {
	t.Helper()

	response, body := doMCPRequest(t, http.MethodGet, requestURL, "", nil)
	if out != nil {
		require.NoError(t, json.Unmarshal([]byte(body), out), "body: %s", body)
	}

	return response
}

// apiRequestWithBearer performs an httpSMS API request authenticated with a
// bearer token (an MCP API delegation token) rather than an x-api-key.
func apiRequestWithBearer(t *testing.T, method, path, token string) (int, string) {
	t.Helper()

	request, err := http.NewRequest(method, apiBaseURL+path, nil)
	require.NoError(t, err)
	request.Header.Set("Authorization", "Bearer "+token)

	response, err := http.DefaultClient.Do(request)
	require.NoError(t, err)
	defer func() { _ = response.Body.Close() }()

	body, err := io.ReadAll(response.Body)
	require.NoError(t, err)

	return response.StatusCode, string(body)
}

// apiRequestWithAPIKey performs an httpSMS API request authenticated with an
// x-api-key, returning the status code and body.
func apiRequestWithAPIKey(t *testing.T, method, path, apiKey string) (int, string) {
	t.Helper()

	request, err := http.NewRequest(method, apiBaseURL+path, nil)
	require.NoError(t, err)
	request.Header.Set("x-api-key", apiKey)

	response, err := http.DefaultClient.Do(request)
	require.NoError(t, err)
	defer func() { _ = response.Body.Close() }()

	body, err := io.ReadAll(response.Body)
	require.NoError(t, err)

	return response.StatusCode, string(body)
}

// setupPhoneForUser registers a phone (and its phone API key) for an arbitrary
// user, mirroring setupPhone but authenticating with that user's own primary
// API key so the MCP test user gets phones of its own.
func setupPhoneForUser(ctx context.Context, t *testing.T, userAPIKeyValue string, messagesPerMinute uint) testPhone {
	t.Helper()

	phoneNumber := randomPhoneNumber()
	fcmToken := "fcm-" + uuid.NewString()

	var created struct {
		Data struct {
			APIKey string `json:"api_key"`
		} `json:"data"`
	}
	requestJSONAs(ctx, t, http.MethodPost, "/v1/phone-api-keys", userAPIKeyValue, map[string]any{
		"name": "mcp-test-key-" + uuid.NewString(),
	}, http.StatusOK, &created)
	require.NotEmpty(t, created.Data.APIKey)

	requestJSONAs(ctx, t, http.MethodPut, "/v1/phones", userAPIKeyValue, map[string]any{
		"phone_number":               phoneNumber,
		"fcm_token":                  fcmToken,
		"messages_per_minute":        messagesPerMinute,
		"max_send_attempts":          2,
		"message_expiration_seconds": 600,
		"sim":                        "SIM1",
	}, http.StatusOK, nil)

	requestJSONAs(ctx, t, http.MethodPut, "/v1/phones/fcm-token", created.Data.APIKey, map[string]any{
		"phone_number": phoneNumber,
		"fcm_token":    fcmToken,
		"sim":          "SIM1",
	}, http.StatusOK, nil)

	waitForPhoneAuthorization(ctx, t, created.Data.APIKey, phoneNumber, 20*time.Second)

	return testPhone{
		PhoneNumber: phoneNumber,
		PhoneAPIKey: created.Data.APIKey,
		FcmToken:    fcmToken,
	}
}

// requestJSONAs is requestJSON for an arbitrary API key: it retries a 401 for
// a short while, because a freshly minted phone API key is not immediately
// visible to every API instance's cache.
func requestJSONAs(
	ctx context.Context,
	t *testing.T,
	method string,
	path string,
	apiKey string,
	payload any,
	expectedStatus int,
	output any,
) {
	t.Helper()

	var encoded []byte
	if payload != nil {
		var err error
		encoded, err = json.Marshal(payload)
		require.NoError(t, err)
	}

	deadline := time.Now().Add(20 * time.Second)
	for {
		request, err := http.NewRequestWithContext(ctx, method, apiBaseURL+path, strings.NewReader(string(encoded)))
		require.NoError(t, err)
		request.Header.Set("x-api-key", apiKey)
		request.Header.Set("Content-Type", "application/json")

		response, err := http.DefaultClient.Do(request)
		require.NoError(t, err)

		body, err := io.ReadAll(response.Body)
		_ = response.Body.Close()
		require.NoError(t, err)

		if response.StatusCode == http.StatusUnauthorized && expectedStatus != http.StatusUnauthorized && time.Now().Before(deadline) {
			time.Sleep(500 * time.Millisecond)
			continue
		}

		require.Equal(t, expectedStatus, response.StatusCode, "%s %s: %s", method, path, string(body))
		if output != nil {
			require.NoError(t, json.Unmarshal(body, output))
		}
		return
	}
}

// receiveSMSAs submits an inbound SMS through the phone endpoint, exactly as
// the Android app does.
func receiveSMSAs(ctx context.Context, t *testing.T, phone testPhone, from, content string) {
	t.Helper()

	requestJSONAs(ctx, t, http.MethodPost, "/v1/messages/receive", phone.PhoneAPIKey, map[string]any{
		"from":      from,
		"to":        phone.PhoneNumber,
		"content":   content,
		"encrypted": false,
		"sim":       "SIM1",
		"timestamp": time.Now().UTC().Format(time.RFC3339Nano),
	}, http.StatusOK, nil)
}

// reportMissedCallAs submits a missed call through the phone endpoint.
func reportMissedCallAs(ctx context.Context, t *testing.T, phone testPhone, from string) {
	t.Helper()

	requestJSONAs(ctx, t, http.MethodPost, "/v1/messages/calls/missed", phone.PhoneAPIKey, map[string]any{
		"from":      from,
		"to":        phone.PhoneNumber,
		"sim":       "SIM1",
		"timestamp": time.Now().UTC().Format(time.RFC3339Nano),
	}, http.StatusOK, nil)
}

// mcpUserAPIKeyValue holds the MCP test user's current primary API key. It
// starts as the seeded value and is updated by the rotation tests, which are
// the only tests allowed to rotate it, so every later assertion authenticates
// with the key that is actually valid.
var mcpUserAPIKeyValue = mcpTestUserAPIKey

// mcpUserAPIKey returns the MCP test user's current primary API key.
func mcpUserAPIKey() string { return mcpUserAPIKeyValue }

// pollMessageStatusAs polls GET /v1/messages/{id} with apiKey until the
// message reaches targetStatus, mirroring pollMessageStatus for a user other
// than the shared integration-test user.
func pollMessageStatusAs(ctx context.Context, t *testing.T, apiKey, messageID, targetStatus string, timeout time.Duration) {
	t.Helper()

	deadline := time.Now().Add(timeout)
	lastStatus := ""
	for time.Now().Before(deadline) {
		request, err := http.NewRequestWithContext(ctx, http.MethodGet, apiBaseURL+"/v1/messages/"+messageID, nil)
		require.NoError(t, err)
		request.Header.Set("x-api-key", apiKey)

		response, err := http.DefaultClient.Do(request)
		require.NoError(t, err)
		body, err := io.ReadAll(response.Body)
		_ = response.Body.Close()
		require.NoError(t, err)

		if response.StatusCode == http.StatusOK {
			var decoded struct {
				Data struct {
					Status string `json:"status"`
				} `json:"data"`
			}
			if json.Unmarshal(body, &decoded) == nil {
				lastStatus = decoded.Data.Status
				if lastStatus == targetStatus {
					return
				}
			}
		}

		time.Sleep(500 * time.Millisecond)
	}

	t.Fatalf("message %s did not reach status %q within %v (last status %q)", messageID, targetStatus, timeout, lastStatus)
}

// mcpContainerLogs returns the MCP container's logs, or ok == false when the
// Docker CLI is unavailable (the log-redaction assertion is then skipped
// rather than failing for an unrelated reason).
func mcpContainerLogs(t *testing.T) (string, bool) {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	command := exec.CommandContext(ctx, "docker", "compose", "logs", "--no-color", "mcp")
	output, err := command.CombinedOutput()
	if err != nil {
		t.Logf("cannot read MCP container logs (%v); skipping the log redaction assertion", err)
		return "", false
	}

	return string(output), true
}
