package tests

import (
	"context"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"database/sql"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"regexp"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
	_ "github.com/lib/pq"
	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// The hosted MCP service under test, as published by tests/docker-compose.yml.
// mcpBaseURL is simultaneously the OAuth issuer, the base of every discovery
// document, and the prefix of the RFC 8707 resource identifier, so it must be
// byte-for-byte the URL the MCP container is configured with (MCP_BASE_URL).
const (
	mcpBaseURL     = "http://localhost:8082"
	mcpEndpointURL = mcpBaseURL + "/mcp"
	mcpResource    = mcpEndpointURL
)

// Identity of the dedicated MCP integration-test user. Every functional MCP
// OAuth flow authenticates as this Firebase UID. Its primary API key is never
// rotated by any test, so it is a constant, not a mutable package global: the
// suite is re-runnable against a live stack and every test may run alone, in
// any order.
const (
	mcpTestUserID     = "mcp-test-user-id"
	mcpTestUserEmail  = "mcp-test@httpsms.com"
	mcpTestUserAPIKey = "mcp-test-user-api-key"
)

// Identity of the dedicated rotation user. It is the only user whose primary
// API key is ever rotated, so no rotation can invalidate a key another test
// authenticates with. The rotation tests never assume its seeded key is still
// current; they derive the current key by rotating once first.
const (
	mcpRotationUserID    = "mcp-rotation-user-id"
	mcpRotationUserEmail = "mcp-rotation@httpsms.com"
)

// Identity of the dedicated create_phone_api_key user. It is the only user
// TestMCPCreatePhoneAPIKey ever authenticates as, so its one
// create_phone_api_key call per run never shares a rate-limit bucket with
// TestMCPToolScopes's missing-scope refusal of the same tool (both of which
// spend budget in the rate limiter regardless of the eventual scope check,
// since the limiter runs before a tool handler ever inspects scope). Without
// this split, two calls against the shared mcpTestUserID bucket would halve
// the number of repeated full-suite runs this test tolerates within an hour.
const (
	mcpPhoneAPIKeyUserID     = "mcp-phone-api-key-user-id"
	mcpPhoneAPIKeyUserEmail  = "mcp-phone-api-key@httpsms.com"
	mcpPhoneAPIKeyUserAPIKey = "mcp-phone-api-key-user-api-key"
)

// Identity of the dedicated isolation user. Nothing in the suite ever creates
// a phone, thread, or message for this user, so "this user sees nothing"
// stays a meaningful assertion on every run. The rate-limit test derives a
// brand-new, throwaway Firebase UID per attempt instead (see
// newRateLimitUserID), so an exhausted hourly bucket never outlives a run.
const (
	mcpIsolatedUserID    = "mcp-rate-limit-user-id"
	mcpIsolatedUserEmail = "mcp-rate-limit@httpsms.com"
	mcpIsolatedUserKey   = "mcp-rate-limit-user-api-key"
)

// Immutable seeded data owned by mcpTestUserID (see seed.sql). No test ever
// mutates or deletes it, so it is a stable prerequisite the preflight can
// validate and the isolation test can assert on. The +1888555xxxx range can
// never collide with the +1800555xxxx numbers randomPhoneNumber() generates.
const (
	mcpSeededPhoneNumber   = "+18885550101"
	mcpSeededPhoneQuery    = "8885550101"
	mcpSeededThreadContact = "+18885550202"
)

// Test-only key material and Firebase configuration, generated by
// generate-firebase-credentials.sh and mounted into the MCP container.
const (
	mcpSigningKeyPath   = "mcp-test-signing-key.pem"
	mcpSigningKeyID     = "mcp-test-key"
	firebaseProjectID   = "httpsms-test"
	firebaseIssuer      = "https://securetoken.google.com/" + firebaseProjectID
	mcpAPIAudience      = "http://api:8000"
	mcpProtocolLatest   = "2026-07-28"
	mcpProtocolPrevious = "2025-11-25"
)

// mcpToolNames is the exact, approved MCP tool catalog. The integration suite
// asserts the served catalog matches it exactly, so adding or renaming a tool
// without updating the design is caught here.
var mcpToolNames = []string{
	"list_phones",
	"send_sms",
	"list_message_threads",
	"list_thread_messages",
	"list_incoming_messages",
	"create_phone_api_key",
	"rotate_user_api_key",
}

// mcpAllScopes is every scope the MCP service issues, in published order.
var mcpAllScopes = []string{
	"phones:read",
	"messages:read",
	"messages:send",
	"phone-api-keys:write",
	"user-api-key:rotate",
}

// transactionIDPattern extracts the authorization transaction ID from the
// rendered consent page. The tests drive the consent form exactly as the
// browser would: they never reach into the MCP service's Redis state.
var transactionIDPattern = regexp.MustCompile(`name="transaction_id" value="([^"]+)"`)

// secretFieldPattern matches every JSON field an httpSMS or OAuth response
// carries a live secret in. redactSecrets replaces their values so a failing
// assertion's message can quote a response body without printing a usable
// access token, refresh token, or API key into the test log.
var secretFieldPattern = regexp.MustCompile(`"(access_token|refresh_token|id_token|api_key|client_secret|registration_access_token)"\s*:\s*"[^"]*"`)

// redactSecrets returns body with every secret field value replaced. Every
// failure message that quotes a token-endpoint, user, or API-key response
// body must pass it through this function first.
func redactSecrets(body string) string {
	return secretFieldPattern.ReplaceAllString(body, `"$1":"[redacted]"`)
}

// assertSecretNotLogged asserts secret never appears in logs, without ever
// writing either the secret or the surrounding log lines into the test output
// (testify's NotContains would print both on failure). description names the
// secret in the failure message instead.
func assertSecretNotLogged(t *testing.T, logs, secret, description string) {
	t.Helper()
	require.NotEmpty(t, secret, "refusing to search the logs for an empty %s", description)
	assert.False(t, strings.Contains(logs, secret), "%s must never appear in the MCP service logs", description)
}

// signingKeyOnce loads the generated RSA signing key at most once per test
// binary: every test that mints a Firebase ID token or an API delegation
// token shares it.
var (
	signingKeyOnce sync.Once
	signingKey     *rsa.PrivateKey
	signingKeyErr  error
)

// tokenResponse is the RFC 6749 token endpoint success body.
type tokenResponse struct {
	AccessToken  string `json:"access_token"`
	TokenType    string `json:"token_type"`
	ExpiresIn    int64  `json:"expires_in"`
	RefreshToken string `json:"refresh_token"`
	Scope        string `json:"scope"`
}

// oauthErrorResponse is the RFC 6749 Section 5.2 error body every direct
// (non-redirect) OAuth error carries.
type oauthErrorResponse struct {
	Error            string `json:"error"`
	ErrorDescription string `json:"error_description"`
}

// mcpSigningKey returns the RSA private key the MCP container signs with and
// the tests sign test Firebase ID tokens and API delegation tokens with.
func mcpSigningKey(t *testing.T) *rsa.PrivateKey {
	t.Helper()

	signingKeyOnce.Do(func() {
		contents, err := os.ReadFile(mcpSigningKeyPath)
		if err != nil {
			signingKeyErr = fmt.Errorf("read %s: %w", mcpSigningKeyPath, err)
			return
		}

		block, _ := pem.Decode(contents)
		if block == nil {
			signingKeyErr = fmt.Errorf("%s does not contain a PEM block", mcpSigningKeyPath)
			return
		}

		if key, err := x509.ParsePKCS1PrivateKey(block.Bytes); err == nil {
			signingKey = key
			return
		}

		parsed, err := x509.ParsePKCS8PrivateKey(block.Bytes)
		if err != nil {
			signingKeyErr = fmt.Errorf("parse %s: %w", mcpSigningKeyPath, err)
			return
		}

		key, ok := parsed.(*rsa.PrivateKey)
		if !ok {
			signingKeyErr = fmt.Errorf("%s is a %T, not an RSA private key", mcpSigningKeyPath, parsed)
			return
		}
		signingKey = key
	})

	require.NoError(t, signingKeyErr, "run `bash generate-firebase-credentials.sh` before the MCP integration tests")
	require.NotNil(t, signingKey)

	return signingKey
}

// signFirebaseTestToken mints a Firebase-style ID token for userID that the
// MCP service verifies against the WireMock-served certificate for
// mcpSigningKeyID. It is the deterministic, offline stand-in for a real
// browser Firebase sign-in.
func signFirebaseTestToken(t *testing.T, userID, email string) string {
	t.Helper()

	now := time.Now().UTC()
	claims := jwt.MapClaims{
		"iss":       firebaseIssuer,
		"aud":       firebaseProjectID,
		"sub":       userID,
		"user_id":   userID,
		"email":     email,
		"auth_time": now.Add(-time.Minute).Unix(),
		"iat":       now.Add(-time.Minute).Unix(),
		"exp":       now.Add(time.Hour).Unix(),
	}

	token := jwt.NewWithClaims(jwt.SigningMethodRS256, claims)
	token.Header["kid"] = mcpSigningKeyID

	signed, err := token.SignedString(mcpSigningKey(t))
	require.NoError(t, err)

	return signed
}

// signAPIDelegationToken mints a downstream API delegation token exactly as
// the MCP service's tool handlers do: issued by the MCP service, audienced to
// the httpSMS API, and bound to one HTTP method and path.
//
// It exists so the tests can prove the API's own delegated-token verifier
// enforces that binding, without going through a tool that can only ever mint
// a correctly bound token.
func signAPIDelegationToken(t *testing.T, userID string, scopes []string, method, path string, options ...func(jwt.MapClaims)) string {
	t.Helper()

	now := time.Now().UTC()
	claims := jwt.MapClaims{
		"iss":         mcpBaseURL,
		"aud":         mcpAPIAudience,
		"sub":         userID,
		"scopes":      scopes,
		"http_method": method,
		"http_path":   path,
		"iat":         now.Unix(),
		"nbf":         now.Unix(),
		"exp":         now.Add(2 * time.Minute).Unix(),
		"jti":         uuid.NewString(),
	}
	for _, option := range options {
		option(claims)
	}

	token := jwt.NewWithClaims(jwt.SigningMethodRS256, claims)
	token.Header["kid"] = mcpSigningKeyID

	signed, err := token.SignedString(mcpSigningKey(t))
	require.NoError(t, err)

	return signed
}

// signFirebaseTokenWithClaims mints a Firebase-style ID token for the MCP test
// user with mutate applied to its claims, for asserting that a token the MCP
// service must reject really is rejected.
func signFirebaseTokenWithClaims(t *testing.T, mutate func(claims jwt.MapClaims)) string {
	t.Helper()

	now := time.Now().UTC()
	claims := jwt.MapClaims{
		"iss":       firebaseIssuer,
		"aud":       firebaseProjectID,
		"sub":       mcpTestUserID,
		"user_id":   mcpTestUserID,
		"email":     mcpTestUserEmail,
		"auth_time": now.Add(-time.Minute).Unix(),
		"iat":       now.Add(-time.Minute).Unix(),
		"exp":       now.Add(time.Hour).Unix(),
	}
	mutate(claims)

	token := jwt.NewWithClaims(jwt.SigningMethodRS256, claims)
	token.Header["kid"] = mcpSigningKeyID

	signed, err := token.SignedString(mcpSigningKey(t))
	require.NoError(t, err)

	return signed
}

// signFirebaseTokenWithKeyID mints an otherwise valid Firebase-style ID token
// under a key ID the Firebase certificate endpoint does not publish.
func signFirebaseTokenWithKeyID(t *testing.T, keyID string) string {
	t.Helper()

	now := time.Now().UTC()
	token := jwt.NewWithClaims(jwt.SigningMethodRS256, jwt.MapClaims{
		"iss":       firebaseIssuer,
		"aud":       firebaseProjectID,
		"sub":       mcpTestUserID,
		"user_id":   mcpTestUserID,
		"email":     mcpTestUserEmail,
		"auth_time": now.Add(-time.Minute).Unix(),
		"iat":       now.Add(-time.Minute).Unix(),
		"exp":       now.Add(time.Hour).Unix(),
	})
	token.Header["kid"] = keyID

	signed, err := token.SignedString(mcpSigningKey(t))
	require.NoError(t, err)

	return signed
}

// pkcePair returns a fresh RFC 7636 code verifier and its S256 challenge.
func pkcePair(t *testing.T) (verifier string, challenge string) {
	t.Helper()

	raw := make([]byte, 32)
	_, err := rand.Read(raw)
	require.NoError(t, err)

	verifier = base64.RawURLEncoding.EncodeToString(raw)
	sum := sha256.Sum256([]byte(verifier))

	return verifier, base64.RawURLEncoding.EncodeToString(sum[:])
}

// noRedirectClient returns an HTTP client that surfaces redirects instead of
// following them: an authorization response redirects to a loopback client
// URL nothing is listening on, and the test needs to read the Location header.
func noRedirectClient() *http.Client {
	return &http.Client{
		Timeout: 30 * time.Second,
		CheckRedirect: func(*http.Request, []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}
}

// registerMCPOAuthClient performs RFC 7591 Dynamic Client Registration
// against the MCP service and returns the assigned client ID and the
// redirect URI it was registered with.
func registerMCPOAuthClient(t *testing.T) (clientID string, redirectURI string) {
	t.Helper()

	redirectURI = "http://localhost:53682/callback/" + uuid.NewString()

	body, err := json.Marshal(map[string]any{
		"client_name":                "httpSMS MCP integration tests",
		"redirect_uris":              []string{redirectURI},
		"grant_types":                []string{"authorization_code", "refresh_token"},
		"response_types":             []string{"code"},
		"token_endpoint_auth_method": "none",
	})
	require.NoError(t, err)

	response, responseBody := doMCPRequest(t, http.MethodPost, mcpBaseURL+"/oauth/register", "application/json", strings.NewReader(string(body)))
	require.Equal(t, http.StatusCreated, response.StatusCode, "register: %s", redactSecrets(responseBody))

	var registered struct {
		ClientID     string   `json:"client_id"`
		RedirectURIs []string `json:"redirect_uris"`
	}
	require.NoError(t, json.Unmarshal([]byte(responseBody), &registered))
	require.NotEmpty(t, registered.ClientID)
	require.Equal(t, []string{redirectURI}, registered.RedirectURIs)

	return registered.ClientID, redirectURI
}

// authorizationCodeParams is one complete, already-approved authorization: the
// code the token endpoint will redeem plus every value the token request must
// echo back.
type authorizationCodeParams struct {
	Code        string
	ClientID    string
	RedirectURI string
	Verifier    string
	State       string
	Issuer      string
	Scopes      []string
}

// requestAuthorizationCode drives a complete browser authorization for userID:
// dynamic client registration, GET /oauth/authorize, and the consent POST that
// carries a signed Firebase ID token. It returns everything needed to redeem
// the resulting code.
func requestAuthorizationCode(t *testing.T, userID, email string, scopes []string) authorizationCodeParams {
	t.Helper()

	clientID, redirectURI := registerMCPOAuthClient(t)
	verifier, challenge := pkcePair(t)
	state := uuid.NewString()

	transactionID := startAuthorization(t, clientID, redirectURI, state, challenge, scopes)
	location := completeFirebaseConsent(t, transactionID, signFirebaseTestToken(t, userID, email), scopes, http.StatusFound)

	redirected, err := url.Parse(location)
	require.NoError(t, err)
	require.Empty(t, redirected.Query().Get("error"), "authorization failed: %s", location)

	code := redirected.Query().Get("code")
	require.NotEmpty(t, code, "no authorization code in %s", location)
	require.Equal(t, state, redirected.Query().Get("state"))

	return authorizationCodeParams{
		Code:        code,
		ClientID:    clientID,
		RedirectURI: redirectURI,
		Verifier:    verifier,
		State:       state,
		Issuer:      redirected.Query().Get("iss"),
		Scopes:      scopes,
	}
}

// startAuthorization performs GET /oauth/authorize and returns the
// authorization transaction ID embedded in the rendered consent page.
func startAuthorization(t *testing.T, clientID, redirectURI, state, challenge string, scopes []string) string {
	t.Helper()

	response, body := getAuthorizePage(t, url.Values{
		"client_id":             {clientID},
		"redirect_uri":          {redirectURI},
		"response_type":         {"code"},
		"state":                 {state},
		"code_challenge":        {challenge},
		"code_challenge_method": {"S256"},
		"resource":              {mcpResource},
		"scope":                 {strings.Join(scopes, " ")},
	})
	require.Equal(t, http.StatusOK, response.StatusCode, "authorize: %s", body)

	match := transactionIDPattern.FindStringSubmatch(body)
	require.Len(t, match, 2, "no transaction_id in the consent page")

	return match[1]
}

// getAuthorizePage performs GET /oauth/authorize with query and returns the
// raw response and body, without following any redirect.
func getAuthorizePage(t *testing.T, query url.Values) (*http.Response, string) {
	t.Helper()

	return doMCPRequest(t, http.MethodGet, mcpBaseURL+"/oauth/authorize?"+query.Encode(), "", nil)
}

// completeFirebaseConsent posts the consent form (transaction, Firebase ID
// token, approved scopes) and returns the Location header of the resulting
// redirect. expectedStatus lets a caller assert a rejected consent instead.
func completeFirebaseConsent(t *testing.T, transactionID, idToken string, approvedScopes []string, expectedStatus int) string {
	t.Helper()

	form := url.Values{
		"transaction_id": {transactionID},
		"id_token":       {idToken},
	}
	form["approved_scopes"] = approvedScopes

	response, body := doMCPRequest(
		t,
		http.MethodPost,
		mcpBaseURL+"/oauth/firebase/complete",
		"application/x-www-form-urlencoded",
		strings.NewReader(form.Encode()),
	)
	require.Equal(
		t,
		expectedStatus,
		response.StatusCode,
		"firebase complete: %s\n(an unexpected 401 usually means WireMock is serving a certificate that no longer matches "+
			"%s: re-run `bash generate-firebase-credentials.sh` and `docker compose up -d --force-recreate wiremock mcp`)",
		redactSecrets(body),
		mcpSigningKeyPath,
	)

	return response.Header.Get("Location")
}

// redeemAuthorizationCode posts the authorization_code grant built from params
// (after applying any overrides) and returns the raw response and body.
func redeemAuthorizationCode(t *testing.T, params authorizationCodeParams, overrides ...func(url.Values)) (*http.Response, string) {
	t.Helper()

	form := url.Values{
		"grant_type":    {"authorization_code"},
		"code":          {params.Code},
		"code_verifier": {params.Verifier},
		"client_id":     {params.ClientID},
		"redirect_uri":  {params.RedirectURI},
		"resource":      {mcpResource},
	}
	for _, override := range overrides {
		override(form)
	}

	return doMCPRequest(t, http.MethodPost, mcpBaseURL+"/oauth/token", "application/x-www-form-urlencoded", strings.NewReader(form.Encode()))
}

// refreshTokens posts the refresh_token grant and returns the raw response and
// body.
func refreshTokens(t *testing.T, refreshToken, clientID string, overrides ...func(url.Values)) (*http.Response, string) {
	t.Helper()

	form := url.Values{
		"grant_type":    {"refresh_token"},
		"refresh_token": {refreshToken},
		"client_id":     {clientID},
	}
	for _, override := range overrides {
		override(form)
	}

	return doMCPRequest(t, http.MethodPost, mcpBaseURL+"/oauth/token", "application/x-www-form-urlencoded", strings.NewReader(form.Encode()))
}

// completeOAuthCodeFlow runs the complete PKCE authorization-code flow for the
// MCP test user and returns the issued tokens.
func completeOAuthCodeFlow(t *testing.T, scopes []string) tokenResponse {
	t.Helper()
	return completeOAuthCodeFlowAs(t, mcpTestUserID, mcpTestUserEmail, scopes)
}

// completeOAuthCodeFlowAs runs the complete PKCE authorization-code flow for
// an arbitrary Firebase UID and returns the issued tokens.
func completeOAuthCodeFlowAs(t *testing.T, userID, email string, scopes []string) tokenResponse {
	t.Helper()

	params := requestAuthorizationCode(t, userID, email, scopes)

	response, body := redeemAuthorizationCode(t, params)
	require.Equal(t, http.StatusOK, response.StatusCode, "token: %s", redactSecrets(body))

	var tokens tokenResponse
	require.NoError(t, json.Unmarshal([]byte(body), &tokens))
	require.NotEmpty(t, tokens.AccessToken)
	require.NotEmpty(t, tokens.RefreshToken)
	require.Equal(t, "Bearer", tokens.TokenType)

	return tokens
}

// bearerTransport attaches a fixed bearer token to every request.
type bearerTransport struct {
	token string
	next  http.RoundTripper
}

func (t *bearerTransport) RoundTrip(request *http.Request) (*http.Response, error) {
	cloned := request.Clone(request.Context())
	cloned.Header.Set("Authorization", "Bearer "+t.token)

	next := t.next
	if next == nil {
		next = http.DefaultTransport
	}
	return next.RoundTrip(cloned)
}

// newMCPClient connects the official MCP Go SDK client to the running MCP
// service over authenticated Streamable HTTP and returns the live session.
//
// protocolVersion must be mcpProtocolLatest: the SDK client always negotiates
// the newest protocol version it supports and offers no exported knob to
// downgrade it. Compatibility with mcpProtocolPrevious is covered by
// callLegacyMCP, which speaks the wire protocol directly and is therefore the
// only way to assert a legacy initialize handshake at all.
func newMCPClient(t *testing.T, accessToken, protocolVersion string, options ...func(*mcp.ClientOptions)) *mcp.ClientSession {
	t.Helper()
	require.Equal(t, mcpProtocolLatest, protocolVersion, "the SDK client only negotiates %s; use callLegacyMCP for %s", mcpProtocolLatest, mcpProtocolPrevious)

	clientOptions := &mcp.ClientOptions{}
	for _, option := range options {
		option(clientOptions)
	}

	client := mcp.NewClient(&mcp.Implementation{Name: "httpsms-integration-tests", Version: "test"}, clientOptions)

	transport := &mcp.StreamableClientTransport{
		Endpoint: mcpEndpointURL,
		HTTPClient: &http.Client{
			Timeout:   60 * time.Second,
			Transport: &bearerTransport{token: accessToken},
		},
		// The MCP service is stateless and never initiates a request of its
		// own, so a standalone SSE stream would only add a connection to
		// tear down.
		DisableStandaloneSSE: true,
	}

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	session, err := client.Connect(ctx, transport, nil)
	require.NoError(t, err)
	t.Cleanup(func() { _ = session.Close() })

	return session
}

// callMCPTool calls name with arguments and fails the test on a protocol-level
// error. A tool-level error (CallToolResult.IsError) is returned to the
// caller, which is what every "this call must be refused" assertion inspects.
func callMCPTool(t *testing.T, session *mcp.ClientSession, name string, arguments any) *mcp.CallToolResult {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	result, err := session.CallTool(ctx, &mcp.CallToolParams{Name: name, Arguments: arguments})
	require.NoError(t, err, "tool %s", name)
	require.NotNil(t, result)

	return result
}

// toolResultText concatenates every text content block of result, which is
// where a tool-level error message is carried.
func toolResultText(result *mcp.CallToolResult) string {
	var builder strings.Builder
	for _, content := range result.Content {
		if text, ok := content.(*mcp.TextContent); ok {
			builder.WriteString(text.Text)
		}
	}
	return builder.String()
}

// decodeToolOutput decodes a successful tool call's structured output into out.
func decodeToolOutput(t *testing.T, result *mcp.CallToolResult, out any) {
	t.Helper()
	require.False(t, result.IsError, "tool call failed: %s", toolResultText(result))
	require.NotNil(t, result.StructuredContent, "tool call returned no structured content")

	encoded, err := json.Marshal(result.StructuredContent)
	require.NoError(t, err)
	require.NoError(t, json.Unmarshal(encoded, out))
}

// jsonRPCResponse is a decoded JSON-RPC response from the MCP endpoint, used
// by the raw-protocol helpers below.
type jsonRPCResponse struct {
	JSONRPC string          `json:"jsonrpc"`
	ID      any             `json:"id"`
	Result  json.RawMessage `json:"result"`
	Error   *struct {
		Code    int             `json:"code"`
		Message string          `json:"message"`
		Data    json.RawMessage `json:"data"`
	} `json:"error"`
}

// callLegacyMCP sends a single JSON-RPC request to the MCP endpoint over raw
// Streamable HTTP, announcing protocolVersion. It is how the suite exercises
// the 2025-11-25 protocol, which the SDK client cannot be asked to negotiate.
func callLegacyMCP(t *testing.T, accessToken, protocolVersion, method string, params any) (*http.Response, jsonRPCResponse) {
	t.Helper()

	payload := map[string]any{
		"jsonrpc": "2.0",
		"id":      uuid.NewString(),
		"method":  method,
	}
	if params != nil {
		payload["params"] = params
	}

	body, err := json.Marshal(payload)
	require.NoError(t, err)

	request, err := http.NewRequest(http.MethodPost, mcpEndpointURL, strings.NewReader(string(body)))
	require.NoError(t, err)
	request.Header.Set("Content-Type", "application/json")
	request.Header.Set("Accept", "application/json, text/event-stream")
	if accessToken != "" {
		request.Header.Set("Authorization", "Bearer "+accessToken)
	}
	if protocolVersion != "" && method != "initialize" {
		request.Header.Set("Mcp-Protocol-Version", protocolVersion)
	}

	response, err := noRedirectClient().Do(request)
	require.NoError(t, err)
	defer func() { _ = response.Body.Close() }()

	raw, err := io.ReadAll(response.Body)
	require.NoError(t, err)

	var decoded jsonRPCResponse
	if len(raw) > 0 && response.StatusCode < http.StatusBadRequest {
		require.NoError(t, json.Unmarshal(raw, &decoded), "response body: %s", string(raw))
	}

	return response, decoded
}

// doMCPRequest performs a single HTTP request against the MCP service and
// returns the response (with its body already drained and closed) and the body.
func doMCPRequest(t *testing.T, method, requestURL, contentType string, body io.Reader) (*http.Response, string) {
	t.Helper()

	request, err := http.NewRequest(method, requestURL, body)
	require.NoError(t, err)
	if contentType != "" {
		request.Header.Set("Content-Type", contentType)
	}

	response, err := noRedirectClient().Do(request)
	require.NoError(t, err)
	defer func() { _ = response.Body.Close() }()

	raw, err := io.ReadAll(response.Body)
	require.NoError(t, err)

	return response, string(raw)
}

// getJSON fetches requestURL and decodes the JSON body into out, returning the
// response for status/header assertions.
func getJSON(t *testing.T, requestURL string, out any) *http.Response {
	t.Helper()

	response, body := doMCPRequest(t, http.MethodGet, requestURL, "", nil)
	if out != nil {
		require.NoError(t, json.Unmarshal([]byte(body), out), "body: %s", body)
	}

	return response
}

// apiRequestWithBearer performs an httpSMS API request authenticated with a
// bearer token (an MCP API delegation token) rather than an x-api-key.
func apiRequestWithBearer(t *testing.T, method, path, token string) (int, string) {
	t.Helper()

	request, err := http.NewRequest(method, apiBaseURL+path, nil)
	require.NoError(t, err)
	request.Header.Set("Authorization", "Bearer "+token)

	response, err := http.DefaultClient.Do(request)
	require.NoError(t, err)
	defer func() { _ = response.Body.Close() }()

	body, err := io.ReadAll(response.Body)
	require.NoError(t, err)

	return response.StatusCode, string(body)
}

// apiRequestWithAPIKey performs an httpSMS API request authenticated with an
// x-api-key, returning the status code and body.
func apiRequestWithAPIKey(t *testing.T, method, path, apiKey string) (int, string) {
	t.Helper()

	request, err := http.NewRequest(method, apiBaseURL+path, nil)
	require.NoError(t, err)
	request.Header.Set("x-api-key", apiKey)

	response, err := http.DefaultClient.Do(request)
	require.NoError(t, err)
	defer func() { _ = response.Body.Close() }()

	body, err := io.ReadAll(response.Body)
	require.NoError(t, err)

	return response.StatusCode, string(body)
}

// setupPhoneForUser registers a phone (and its phone API key) for an arbitrary
// user, mirroring setupPhone but authenticating with that user's own primary
// API key so the MCP test user gets phones of its own.
func setupPhoneForUser(ctx context.Context, t *testing.T, userAPIKeyValue string, messagesPerMinute uint) testPhone {
	t.Helper()

	phoneNumber := randomPhoneNumber()
	fcmToken := "fcm-" + uuid.NewString()

	var created struct {
		Data struct {
			APIKey string `json:"api_key"`
		} `json:"data"`
	}
	requestJSONAs(ctx, t, http.MethodPost, "/v1/phone-api-keys", userAPIKeyValue, map[string]any{
		"name": "mcp-test-key-" + uuid.NewString(),
	}, http.StatusOK, &created)
	require.NotEmpty(t, created.Data.APIKey)

	requestJSONAs(ctx, t, http.MethodPut, "/v1/phones", userAPIKeyValue, map[string]any{
		"phone_number":               phoneNumber,
		"fcm_token":                  fcmToken,
		"messages_per_minute":        messagesPerMinute,
		"max_send_attempts":          2,
		"message_expiration_seconds": 600,
		"sim":                        "SIM1",
	}, http.StatusOK, nil)

	requestJSONAs(ctx, t, http.MethodPut, "/v1/phones/fcm-token", created.Data.APIKey, map[string]any{
		"phone_number": phoneNumber,
		"fcm_token":    fcmToken,
		"sim":          "SIM1",
	}, http.StatusOK, nil)

	waitForPhoneAuthorization(ctx, t, created.Data.APIKey, phoneNumber, 20*time.Second)

	return testPhone{
		PhoneNumber: phoneNumber,
		PhoneAPIKey: created.Data.APIKey,
		FcmToken:    fcmToken,
	}
}

// requestJSONAs is requestJSON for an arbitrary API key: it retries a 401 for
// a short while, because a freshly minted phone API key is not immediately
// visible to every API instance's cache.
func requestJSONAs(
	ctx context.Context,
	t *testing.T,
	method string,
	path string,
	apiKey string,
	payload any,
	expectedStatus int,
	output any,
) {
	t.Helper()

	var encoded []byte
	if payload != nil {
		var err error
		encoded, err = json.Marshal(payload)
		require.NoError(t, err)
	}

	deadline := time.Now().Add(20 * time.Second)
	for {
		request, err := http.NewRequestWithContext(ctx, method, apiBaseURL+path, strings.NewReader(string(encoded)))
		require.NoError(t, err)
		request.Header.Set("x-api-key", apiKey)
		request.Header.Set("Content-Type", "application/json")

		response, err := http.DefaultClient.Do(request)
		require.NoError(t, err)

		body, err := io.ReadAll(response.Body)
		_ = response.Body.Close()
		require.NoError(t, err)

		if response.StatusCode == http.StatusUnauthorized && expectedStatus != http.StatusUnauthorized && time.Now().Before(deadline) {
			time.Sleep(500 * time.Millisecond)
			continue
		}

		require.Equal(t, expectedStatus, response.StatusCode, "%s %s: %s", method, path, string(body))
		if output != nil {
			require.NoError(t, json.Unmarshal(body, output))
		}
		return
	}
}

// receiveSMSAs submits an inbound SMS through the phone endpoint, exactly as
// the Android app does.
func receiveSMSAs(ctx context.Context, t *testing.T, phone testPhone, from, content string) {
	t.Helper()

	requestJSONAs(ctx, t, http.MethodPost, "/v1/messages/receive", phone.PhoneAPIKey, map[string]any{
		"from":      from,
		"to":        phone.PhoneNumber,
		"content":   content,
		"encrypted": false,
		"sim":       "SIM1",
		"timestamp": time.Now().UTC().Format(time.RFC3339Nano),
	}, http.StatusOK, nil)
}

// reportMissedCallAs submits a missed call through the phone endpoint.
func reportMissedCallAs(ctx context.Context, t *testing.T, phone testPhone, from string) {
	t.Helper()

	requestJSONAs(ctx, t, http.MethodPost, "/v1/messages/calls/missed", phone.PhoneAPIKey, map[string]any{
		"from":      from,
		"to":        phone.PhoneNumber,
		"sim":       "SIM1",
		"timestamp": time.Now().UTC().Format(time.RFC3339Nano),
	}, http.StatusOK, nil)
}

// newRateLimitUserID returns a brand-new, throwaway Firebase UID for the
// rate-limit test. Rate-limit budgets are keyed by user and tool, so a fresh
// UID always starts with an untouched budget: the rate-limit assertion is
// therefore exactly as strong as before while surviving repeated runs against
// the same live stack. Unlike a delegated MCP call to a route the API
// authenticates purely off the token's own claims, create_phone_api_key's
// delegated token is only ever honored for a subject the API can load a real
// users row for (see MCPDelegationAuth), so seedRateLimitUser must create one
// before this UID can mint anything.
func newRateLimitUserID() string {
	return "mcp-rate-limit-" + uuid.NewString()
}

// cockroachDSN is the CockroachDB connection string the test binary uses to
// seed and clean up throwaway rate-limit users directly, mirroring
// DATABASE_URL in tests/.env.test with the host-mapped port (26257) the
// stack publishes for exactly this purpose, rather than the in-network
// "cockroachdb" hostname the containers themselves resolve.
const cockroachDSN = "postgresql://root@localhost:26257/httpsms?sslmode=disable"

// seedRateLimitUser inserts a brand-new user row for a throwaway rate-limit
// UID directly into CockroachDB -- the same mechanism tests/seed.sql uses --
// and registers a t.Cleanup that deletes it, and any phone API keys it ends
// up owning, once the test finishes. Rate-limit budgets are still keyed by
// UID alone, so a fresh UID starts with an untouched budget regardless of
// this row's lifetime; seeding and deleting it around the test just keeps
// create_phone_api_key from failing 401 without leaving a permanent row
// behind, unlike a fixed seeded user shared across every run.
//
// The insert is deliberately minimal, mirroring the columns tests/seed.sql
// sets for every other seeded user: id, email, api_key, timezone, and
// subscription_name, with created_at/updated_at defaulted to NOW().
func seedRateLimitUser(t *testing.T) (userID string, apiKey string) {
	t.Helper()

	db, err := sql.Open("postgres", cockroachDSN)
	require.NoError(t, err, "open CockroachDB connection for rate-limit user setup")
	t.Cleanup(func() { _ = db.Close() })
	require.NoError(t, db.PingContext(context.Background()), "connect to CockroachDB at %s to seed the rate-limit user", cockroachDSN)

	userID = newRateLimitUserID()
	apiKey = "mcp-rate-limit-key-" + uuid.NewString()

	_, err = db.ExecContext(context.Background(), `
		INSERT INTO users (id, email, api_key, timezone, subscription_name, created_at, updated_at)
		VALUES ($1, $2, $3, 'UTC', 'pro-monthly', NOW(), NOW())
		ON CONFLICT (id) DO NOTHING
	`, userID, userID+"@httpsms.com", apiKey)
	require.NoError(t, err, "seed rate-limit user %s", userID)

	t.Cleanup(func() { cleanupRateLimitUser(t, userID) })

	return userID, apiKey
}

// cleanupRateLimitUser best-effort deletes the phone API keys and user row
// seedRateLimitUser created for userID. It never fails the test: a stack
// that has already been torn down (or a connection that cannot be reopened
// from a t.Cleanup running after other cleanups closed it) must not turn a
// passing rate-limit assertion into a failure over housekeeping. Any error
// is logged instead, exactly as the suite's other best-effort cleanups do.
func cleanupRateLimitUser(t *testing.T, userID string) {
	t.Helper()

	db, err := sql.Open("postgres", cockroachDSN)
	if err != nil {
		t.Logf("cannot open CockroachDB connection to clean up rate-limit user %s: %v", userID, err)
		return
	}
	defer func() { _ = db.Close() }()

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	if _, err := db.ExecContext(ctx, `DELETE FROM phone_api_keys WHERE user_id = $1`, userID); err != nil {
		t.Logf("cannot delete phone API keys for rate-limit user %s: %v", userID, err)
		return
	}
	if _, err := db.ExecContext(ctx, `DELETE FROM users WHERE id = $1`, userID); err != nil {
		t.Logf("cannot delete rate-limit user %s: %v", userID, err)
	}
}

// countPhoneAPIKeys returns how many phone_api_keys rows userID owns. The
// rate-limit test uses it to assert every pre-budget create_phone_api_key
// call actually persisted a key -- not just that the MCP service reported
// success -- before the call that must be rate limited.
func countPhoneAPIKeys(t *testing.T, userID string) int {
	t.Helper()

	db, err := sql.Open("postgres", cockroachDSN)
	require.NoError(t, err, "open CockroachDB connection to count phone API keys for %s", userID)
	defer func() { _ = db.Close() }()

	var count int
	err = db.QueryRowContext(context.Background(), `SELECT count(*) FROM phone_api_keys WHERE user_id = $1`, userID).Scan(&count)
	require.NoError(t, err, "count phone API keys for %s", userID)

	return count
}

// pollMessageStatusAs polls GET /v1/messages/{id} with apiKey until the
// message reaches targetStatus, mirroring pollMessageStatus for a user other
// than the shared integration-test user.
func pollMessageStatusAs(ctx context.Context, t *testing.T, apiKey, messageID, targetStatus string, timeout time.Duration) {
	t.Helper()

	deadline := time.Now().Add(timeout)
	lastStatus := ""
	for time.Now().Before(deadline) {
		request, err := http.NewRequestWithContext(ctx, http.MethodGet, apiBaseURL+"/v1/messages/"+messageID, nil)
		require.NoError(t, err)
		request.Header.Set("x-api-key", apiKey)

		response, err := http.DefaultClient.Do(request)
		require.NoError(t, err)
		body, err := io.ReadAll(response.Body)
		_ = response.Body.Close()
		require.NoError(t, err)

		if response.StatusCode == http.StatusOK {
			var decoded struct {
				Data struct {
					Status string `json:"status"`
				} `json:"data"`
			}
			if json.Unmarshal(body, &decoded) == nil {
				lastStatus = decoded.Data.Status
				if lastStatus == targetStatus {
					return
				}
			}
		}

		time.Sleep(500 * time.Millisecond)
	}

	t.Fatalf("message %s did not reach status %q within %v (last status %q)", messageID, targetStatus, timeout, lastStatus)
}

// mcpContainerLogs returns the MCP container's logs, or ok == false when the
// Docker CLI is unavailable (the log-redaction assertion is then skipped
// rather than failing for an unrelated reason).
func mcpContainerLogs(t *testing.T) (string, bool) {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	command := exec.CommandContext(ctx, "docker", "compose", "logs", "--no-color", "mcp")
	output, err := command.CombinedOutput()
	if err != nil {
		t.Logf("cannot read MCP container logs (%v); skipping the log redaction assertion", err)
		return "", false
	}

	return string(output), true
}

// resetStackInstruction is the exact recovery procedure for a stack whose
// immutable seeded prerequisites are missing or stale. It is only ever
// printed when a prerequisite really is invalid: a routine repeated run
// against a healthy stack never needs it, because no test mutates anything
// the preflight checks.
const resetStackInstruction = "reset the stack and re-seed it:\n" +
	"    cd tests\n" +
	"    docker compose down -v\n" +
	"    docker compose up -d --build --wait mcp\n" +
	"    docker compose up -d seed && docker compose wait seed"

var (
	mcpPreflightOnce sync.Once
	mcpPreflightErr  error
)

// requireMCPStack runs the (fast, once-per-binary) preflight every MCP test
// starts with: the generated signing key exists, the API and MCP services
// answer their health checks, and every immutable seeded prerequisite is
// present. It fails with the exact command to run rather than letting a
// missing prerequisite surface later as an unrelated assertion failure.
func requireMCPStack(t *testing.T) {
	t.Helper()

	mcpPreflightOnce.Do(func() { mcpPreflightErr = mcpPreflight() })
	if mcpPreflightErr != nil {
		t.Fatalf("MCP integration preflight failed: %v", mcpPreflightErr)
	}
}

// mcpPreflight validates every prerequisite the MCP suite cannot run without.
// It deliberately checks only immutable state: the rotation user's primary
// API key is never checked, because rotating it is exactly what the rotation
// tests do, and requiring its seeded value to still be current is what made
// the suite non-re-runnable in the first place.
func mcpPreflight() error {
	if _, err := os.Stat(mcpSigningKeyPath); err != nil {
		return fmt.Errorf("%s is missing: run `bash generate-firebase-credentials.sh` in tests/ (%w)", mcpSigningKeyPath, err)
	}

	client := &http.Client{Timeout: 10 * time.Second}
	services := []struct{ name, url string }{
		{"the httpSMS API", apiBaseURL + "/health"},
		{"the MCP service", mcpBaseURL + "/health"},
	}
	for _, service := range services {
		if err := preflightStatusOK(client, service.url, ""); err != nil {
			return fmt.Errorf("%s is not reachable: %w\nstart the stack with `docker compose up -d --build --wait mcp` in tests/", service.name, err)
		}
	}

	seededUsers := []struct{ name, apiKey string }{
		{"the MCP test user (" + mcpTestUserID + ")", mcpTestUserAPIKey},
		{"the isolated user (" + mcpIsolatedUserID + ")", mcpIsolatedUserKey},
		{"the phone API key user (" + mcpPhoneAPIKeyUserID + ")", mcpPhoneAPIKeyUserAPIKey},
	}
	for _, user := range seededUsers {
		if err := preflightStatusOK(client, apiBaseURL+"/v1/users/me", user.apiKey); err != nil {
			return fmt.Errorf("the seeded primary API key of %s is not valid: %w\nno test ever rotates it, so %s", user.name, err, resetStackInstruction)
		}
	}

	if err := preflightContains(
		client,
		apiBaseURL+"/v1/phones?skip=0&limit=5&query="+url.QueryEscape(mcpSeededPhoneQuery),
		mcpTestUserAPIKey,
		mcpSeededPhoneNumber,
	); err != nil {
		return fmt.Errorf("the seeded MCP phone %s is missing: %w\n%s", mcpSeededPhoneNumber, err, resetStackInstruction)
	}

	if err := preflightContains(
		client,
		apiBaseURL+"/v1/message-threads?skip=0&limit=5&owner="+url.QueryEscape(mcpSeededPhoneNumber),
		mcpTestUserAPIKey,
		mcpSeededThreadContact,
	); err != nil {
		return fmt.Errorf("the seeded MCP message thread %s -> %s is missing: %w\n%s", mcpSeededPhoneNumber, mcpSeededThreadContact, err, resetStackInstruction)
	}

	return nil
}

// preflightStatusOK performs a single GET and requires a 200. apiKey may be
// empty for an unauthenticated health endpoint. The response body is never
// included in the error: /v1/users/me carries the user's primary API key.
func preflightStatusOK(client *http.Client, requestURL, apiKey string) error {
	status, _, err := preflightGet(client, requestURL, apiKey)
	if err != nil {
		return err
	}
	if status != http.StatusOK {
		return fmt.Errorf("GET %s returned %d", requestURL, status)
	}
	return nil
}

// preflightContains performs a single authenticated GET and requires the
// response to contain expected. Only expected -- never the response body,
// which may carry secrets -- appears in the error.
func preflightContains(client *http.Client, requestURL, apiKey, expected string) error {
	status, body, err := preflightGet(client, requestURL, apiKey)
	if err != nil {
		return err
	}
	if status != http.StatusOK {
		return fmt.Errorf("GET %s returned %d", requestURL, status)
	}
	if !strings.Contains(body, expected) {
		return fmt.Errorf("GET %s did not return %s", requestURL, expected)
	}
	return nil
}

// preflightGet performs one plain GET and returns its status and body.
func preflightGet(client *http.Client, requestURL, apiKey string) (int, string, error) {
	request, err := http.NewRequest(http.MethodGet, requestURL, nil)
	if err != nil {
		return 0, "", err
	}
	if apiKey != "" {
		request.Header.Set("x-api-key", apiKey)
	}

	response, err := client.Do(request)
	if err != nil {
		return 0, "", err
	}
	defer func() { _ = response.Body.Close() }()

	body, err := io.ReadAll(response.Body)
	if err != nil {
		return response.StatusCode, "", err
	}

	return response.StatusCode, string(body), nil
}

// assertAPIKeyAccepted asserts apiKey still authenticates against the API.
// The response body carries the user's primary API key, so only its redacted
// form ever reaches the failure message.
func assertAPIKeyAccepted(t *testing.T, apiKey, description string) {
	t.Helper()

	status, body := apiRequestWithAPIKey(t, http.MethodGet, "/v1/users/me", apiKey)
	require.Equal(t, http.StatusOK, status, "%s: %s", description, redactSecrets(body))
}

// assertAPIKeyRejected asserts apiKey no longer authenticates against the
// API, again without ever printing an unredacted body.
func assertAPIKeyRejected(t *testing.T, apiKey, description string) {
	t.Helper()

	status, body := apiRequestWithAPIKey(t, http.MethodGet, "/v1/users/me", apiKey)
	assert.Equal(t, http.StatusUnauthorized, status, "%s: %s", description, redactSecrets(body))
}

// bootstrapPrimaryAPIKey rotates userID's primary httpSMS API key through a
// delegation token this test binary mints itself, and returns the brand-new
// key.
//
// It is how a test that must start from a primary API key whose value it knows
// obtains one, instead of assuming a seeded key is still current: a seeded
// primary key is only ever valid until the first run of the first test that
// rotates it, which is exactly what made this suite non-re-runnable. The
// delegation token is bound to this one method and path, so the API's own
// delegated-MCP verifier accepts it for nothing else.
func bootstrapPrimaryAPIKey(t *testing.T, userID string) string {
	t.Helper()

	path := "/v1/users/" + url.PathEscape(userID) + "/api-keys"
	token := signAPIDelegationToken(t, userID, []string{"user-api-key:rotate"}, http.MethodDelete, path)

	status, body := apiRequestWithBearer(t, http.MethodDelete, path, token)
	require.Equal(t, http.StatusOK, status, "cannot bootstrap a primary API key for %s: %s", userID, redactSecrets(body))

	var rotated struct {
		Data struct {
			ID     string `json:"id"`
			APIKey string `json:"api_key"`
		} `json:"data"`
	}
	require.NoError(t, json.Unmarshal([]byte(body), &rotated))
	require.Equal(t, userID, rotated.Data.ID)
	require.NotEmpty(t, rotated.Data.APIKey)

	return rotated.Data.APIKey
}

// currentRateLimitWindow returns the start of the UTC hour the MCP service's
// rate limiter is currently counting hourly budgets in. It mirrors
// time.Now().UTC().Truncate(time.Hour) in mcp/internal/server/rate_limit.go.
func currentRateLimitWindow() time.Time {
	return time.Now().UTC().Truncate(time.Hour)
}

// waitForRateLimitWindowHeadroom blocks until the current hourly rate-limit
// window has enough time left for a whole exhaust-the-budget sequence.
//
// The hourly budget is counted in fixed UTC hour windows, so a sequence that
// straddles the top of the hour would see the counter reset midway and the
// final call succeed. Waiting out the last seconds of a window keeps the
// assertion exactly as strict (the call after the budget really must be
// refused) instead of weakening it to tolerate a reset.
func waitForRateLimitWindowHeadroom(t *testing.T) {
	t.Helper()

	const headroom = 30 * time.Second

	remaining := time.Until(currentRateLimitWindow().Add(time.Hour))
	if remaining >= headroom {
		return
	}

	t.Logf("only %s left in the current UTC rate-limit window; waiting for the next one", remaining.Round(time.Second))
	time.Sleep(remaining + time.Second)
}
