name: web

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  deployments: write

defaults:
  run:
    working-directory: ./web

jobs:
  validate:
    name: Validate
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [24]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 11

      - name: Install dependencies 📦
        run: pnpm install

      - name: Run linter 👀
        run: pnpm lint

      - name: Run tests 🧪
        run: pnpm test

      - name: Build 🏗️
        run: mv .env.production .env && echo "GITHUB_SHA=${GITHUB_SHA}" >> .env && pnpm run generate

  deploy:
    name: Deploy
    needs: validate
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup Node 🟢
        uses: actions/setup-node@v4
        with:
          node-version: '24.18'

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 11

      - name: Install dependencies 📦
        run: pnpm install

      - name: Build 🏗️
        run: mv .env.production .env && echo "GITHUB_SHA=${GITHUB_SHA}" >> .env && pnpm run generate

      - name: Cloudflare Deploy 🚀
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy web/.output/public --project-name=httpsms
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Firebase Deploy 🚀
        uses: FirebaseExtended/action-hosting-deploy@500ac625ca2dd40cbd15f7659af953801858032a
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          channelId: live
          entryPoint: "./web"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_HTTPSMS_86C51 }}"
          projectId: httpsms-86c51
